apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-cm-reader
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-cm-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: scaletest
roleRef:
  kind: ClusterRole
  name: cluster-cm-reader
  apiGroup: rbac.authorization.k8s.io
