apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    prometheus.io/port: "9101"
    prometheus.io/scrape: "true"
  labels:
    app: cmdriver
  name: cmdriver
  namespace: scaletest
spec:
  template:
    metadata:
      labels:
        app: cmdriver
    spec:
      containers:
      - name: cmdriver
        image: marceloamaral/cmdriver:latest
        command:
          - "/cmdriver"
          - "-lambda=$(LAMBDA)"
          - "-maxpop=$(MAXPOP)"
          - "-n=$(NUM)"
          - "-log_dir=$(LOGDIR)"
          - "-waitBeforeTerminate=$(WAITBEFORETERMINATE)"
        env:
        - name: LAMBDA
          value: "10"
        - name: MAXPOP
          value: "100"
        - name: NUM
          value: "300"
        - name: LOGDIR
          value: /results
        - name: WAITBEFORETERMINATE
          value: "15"
        ports:
        - containerPort: 9101
        volumeMounts:
        - mountPath: /results
          name: results
      restartPolicy: Never
      volumes:
      - name: results
        emptyDir: {}

