apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wardler
  namespace: scaletest
rules:
- apiGroups:
  - wardle.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wardler
subjects:
- kind: ServiceAccount
  name: default
  namespace: scaletest
roleRef:
  kind: ClusterRole
  name: wardler
  apiGroup: rbac.authorization.k8s.io
