apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: flunder-logger
  namespace: scaletest
spec:
  selector:
    matchLabels:
      app: flunder-logger
  template:
    metadata:
      labels:
        app: flunder-logger
    spec:
      containers:
      - image: mspreitz/flunder-logger:latest
        name: logger
